on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "feature/**"

name: PR-Pipeline

env:
  DEV_DIRECTORY: dev
  REGION: eu-west-1

jobs:
  validate:
    name: Validate module
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.REGION }}
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

  version:
    name: Bump version
    runs-on: ubuntu-latest
    environment: dev
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Installing packages
        run: yarn install

      - name: Configuring Git user email
        run: git config --global user.email "actions@github.com"

      - name: Configuring Git user name
        run: git config --global user.name "Github Action Bot"

      - name: bump
        run: yarn release:beta --dry-run

      # - name: Pushing Release tag
      #  run: git push --follow-tags origin HEAD:${GITHUB_HEAD_REF}
